#!/bin/sh

ntp_server=$1

logger -t chrony-set-ntp-server "ntp server: '${ntp_server}'"

if [ -z "$ntp_server" ]
then
    logger -t chrony-set-ntp-server "standard config"
    cp /etc/chrony/chrony.conf.orig /etc/chrony/chrony.conf
    /etc/init.d/chronyd restart
else
    logger -t chrony-set-ntp-server "custom config"
    cp /etc/chrony/chrony.conf.base /etc/chrony/chrony.conf
    echo "pool ${ntp_server} iburst" >> /etc/chrony/chrony.conf
    /etc/init.d/chronyd restart
fi
